import type { Metadata } from "next";

import { Navigation, Footer } from "@/components";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html id="html-root" lang="en">
      <body className="bg-color-body mt-6 dark:bg-[#242535]  ">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
