import "./globals.css";
import React from "react";
import type { Metadata } from "next";

import { Providers } from "@/utils";
import { Navigation, Footer } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-color-body mt-6 ">
        <Navigation />

        <Providers>{children}</Providers>

        <Footer />
      </body>
    </html>
  );
}
